export function getSystemIP(): Promise<string>;
export function getDeviceFingerprint(): Promise<string>;
export function isBot(userAgent: string): boolean;
export function checkCookieDuplication(cookieName: string): boolean;
export function verifyCountry(expectedCountry: string): Promise<boolean>;
export function isUsingVPN(): Promise<boolean>;
export function techDetails(): {
    os: string;
    isIE: boolean;
    isUC: boolean;
    geoIp: {};
    isBot: boolean;
    isMac: boolean;
    isBada: boolean;
    isCurl: boolean;
    isEdge: boolean;
    isSilk: boolean;
    isiPad: boolean;
    isiPod: boolean;
    source: string;
    browser: string;
    isAmaya: boolean;
    isFlock: boolean;
    isLinux: boolean;
    isOpera: boolean;
    isWinJs: boolean;
    version: string;
    isChrome: boolean;
    isMobile: boolean;
    isSafari: boolean;
    isTablet: boolean;
    isWebkit: boolean;
    isWechat: boolean;
    isiPhone: boolean;
    platform: string;
    isAndroid: boolean;
    isCaptive: boolean;
    isDesktop: boolean;
    isFirefox: boolean;
    isLinux64: boolean;
    isOmniWeb: boolean;
    isSamsung: boolean;
    isSmartTV: boolean;
    isWindows: boolean;
    isChromeOS: boolean;
    isElectron: boolean;
    isEpiphany: boolean;
    isFacebook: boolean;
    isAlamoFire: boolean;
    isKonqueror: boolean;
    isPhantomJS: boolean;
    isRaspberry: boolean;
    isSeaMonkey: boolean;
    isYaBrowser: boolean;
    isBlackberry: boolean;
    isKindleFire: boolean;
    isMobileNative: boolean;
    isiPhoneNative: boolean;
    isAndroidNative: boolean;
    isAndroidTablet: boolean;
    isAuthoritative: boolean;
    silkAccelerated: boolean;
};